### ISSUE TITLE
[SmartStageGPU] WDL model run failed when enable do_smart_stage_gpu

### ISSUE THREAD

**Issue by JackMoriarty** [alibaba/DeepRec#384]
Error Message:
2022-08-18 03:56:14.343434: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/I3/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.343434: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/I6/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.343434: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/I9/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.343434: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/I4/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.343436: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/I10/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.343434: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/I1/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.343437: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/I5/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.343440: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/bias_weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.343567: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/I7/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.344576: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/I8/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.344603: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/I12/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.344691: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/I11/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.344791: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/I13/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.344905: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/I2/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345142: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C13/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345153: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C19/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345161: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C2/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345169: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C24/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345179: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C5/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345192: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C11/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345200: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C23/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345209: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C25/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345217: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C14/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345244: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C6/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345253: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C8/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345264: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C9/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345279: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C3/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345288: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C26/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345300: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C21/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345308: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C16/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345329: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C18/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345337: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C10/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345345: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C15/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345355: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C12/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345363: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C17/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345375: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C7/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345386: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C22/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345394: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C20/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345402: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C1/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
2022-08-18 03:56:14.345410: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:400 : Invalid argument: Trying to access resource linear/linear_model/C4/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
Traceback (most recent call last):
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Trying to access resource linear/linear_model/I6/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
	 [[{{node linear/linear_model/I6/weights/part_0/Assign}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 839, in <module>
    main()
  File "train.py", line 612, in main
    checkpoint_dir, tf_config, server)
  File "train.py", line 477, in train
    config=sess_config) as sess:
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 670, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1101, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 812, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1294, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1299, in _create_session
    return self._sess_creator.create_session()
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 965, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 734, in create_session
    init_fn=self._scaffold.init_fn)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/training/session_manager.py", line 306, in prepare_session
    sess.run(init_op, feed_dict=init_feed_dict)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Trying to access resource linear/linear_model/I6/weights/part_0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
	 [[node linear/linear_model/I6/weights/part_0/Assign (defined at /home/pai/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'linear/linear_model/I6/weights/part_0/Assign':
  File "train.py", line 839, in <module>
    main()
  File "train.py", line 608, in main
    dense_layer_partitioner=dense_layer_partitioner)
  File "train.py", line 133, in __init__
    self._create_model()
  File "train.py", line 216, in _create_model
    trainable=True)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/feature_column/feature_column.py", line 505, in linear_model
    retval = linear_model_layer(features)  # pylint: disable=not-callable
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 871, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 234, in wrapper
    return converted_call(f, options, args, kwargs)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 439, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 330, in _call_unconverted
    return f(*args, **kwargs)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/feature_column/feature_column.py", line 697, in call
    weighted_sum = layer(builder)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/layers/base.py", line 564, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 911, in __call__
    self._maybe_build(inputs)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2163, in _maybe_build
    self.build(input_shapes)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/feature_column/feature_column.py", line 576, in build
    trainable=self.trainable)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1724, in add_variable
    return self.add_weight(*args, **kwargs)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/layers/base.py", line 477, in add_weight
    **kwargs)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 546, in add_weight
    aggregation=aggregation)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/base.py", line 724, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1967, in get_variable
    aggregation=aggregation)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1525, in get_variable
    aggregation=aggregation)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 805, in get_variable
    ht_partition_num=ht_partition_num)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 697, in _true_getter
    ht_partition_num=ht_partition_num)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1035, in _get_partitioned_variable
    ht_partition_num=ht_partition_num)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1215, in _get_single_variable
    ht_partition_num=ht_partition_num)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 448, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 409, in _variable_v1_call
    ht_partition_num=ht_partition_num)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 382, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 3330, in default_variable_creator
    shape=shape)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 452, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1407, in __init__
    distribute_strategy=distribute_strategy)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1581, in _init_from_args
    name=n))
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_resource_variable_ops.py", line 196, in assign_variable_op
    "AssignVariableOp", resource=resource, value=value, name=name)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/pai/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by JackMoriarty** [comment]
fix https://github.com/alibaba/DeepRec/pull/512
