### ISSUE TITLE
N10tensorflow15EmbeddingVarGPUIxfEE not found.

### ISSUE THREAD

**Issue by zhaozheng09** [alibaba/DeepRec#595]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Centos
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:-
- TensorFlow installed from (source or binary):source
- TensorFlow version: 1.15
- Python version:3.6
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source):0.26.1
- GCC/Compiler version (if compiling from source):7.5.0
- CUDA/cuDNN version:  11.6
- GPU model and memory: yes

**Describe the problem**
/root/DeepRec/addons/sparse_operation_kit/example/demo.py failed .

**Provide the exact sequence of commands / steps that you executed before running into the problem**
/root/DeepRec/addons/sparse_operation_kit/example/demo.py success .

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

2022-12-16 07:08:48.469988: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at embedding_collection.cc:770 : Invalid argument: Trying to access resource using the wrong type. Expected N10tensorflow12EmbeddingVarIxfEE got N10tensorflow15EmbeddingVarGPUIxfEE
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Trying to access resource using the wrong type. Expected N10tensorflow12EmbeddingVarIxfEE got N10tensorflow15EmbeddingVarGPUIxfEE
	 [[{{node LookupForward/LookupForwardEmbeddingVarGPU}}]]
	 [[PostprocessingForward/PostprocessingForward/_25]]
  (1) Invalid argument: Trying to access resource using the wrong type. Expected N10tensorflow12EmbeddingVarIxfEE got N10tensorflow15EmbeddingVarGPUIxfEE
	 [[{{node LookupForward/LookupForwardEmbeddingVarGPU}}]]
0 successful operations.
0 derived errors ignored.

**Comment by zhaozheng09** [comment]
./configure need  gpu env.
